package com.dastyar.app.audio

import android.content.Context
import android.media.MediaPlayer
import com.dastyar.app.ai.AiClient
import java.io.File

/**
 * Plays the welcome message. The audio is generated by the real TTS service and
 * cached on disk, so it does not depend on the phone's built-in TTS engine.
 */
object VoicePlayer {

    private var player: MediaPlayer? = null

    private fun cacheFile(ctx: Context, key: String): File {
        val dir = File(ctx.filesDir, "voice").apply { mkdirs() }
        return File(dir, "$key.wav")
    }

    /** Generates the greeting for [name] once, then reuses the cached file. */
    suspend fun ensureWelcome(ctx: Context, name: String): Result<File> {
        val safeName = name.ifBlank { "دوست من" }
        val key = "welcome_" + safeName.hashCode()
        val file = cacheFile(ctx, key)
        if (file.exists() && file.length() > 2000) return Result.success(file)

        val text = "خوش اومدی $safeName جان. من دستیار تو هستم."
        return AiClient.textToSpeech(text).map { bytes ->
            file.writeBytes(bytes)
            file
        }
    }

    fun play(file: File) {
        try {
            stop()
            player = MediaPlayer().apply {
                setDataSource(file.absolutePath)
                setOnCompletionListener { stop() }
                prepare()
                start()
            }
        } catch (_: Exception) {
        }
    }

    fun stop() {
        try {
            player?.stop()
            player?.release()
        } catch (_: Exception) {
        } finally {
            player = null
        }
    }
}
